# Site/SEO settings
email: nie.suzanne01@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: The Loop
title: The Loop Blog ⭕
description: >
  This is the quarantine blog featuring the Loop. [made with the barber theme, http://barber.samesies.io]
url: http://barber.samesies.io
twitter_username: no twitter
default_img: /assets/images/loopprofile.jpg
social:
  - name: instagram
    url: https://www.instagram.com/suzannenie/
  - name: instagram
    url: https://www.instagram.com/kayeetgeorge/
  - name: instagram
    url: https://www.instagram.com/joanne.nie/
  - name: instagram
    url: https://www.instagram.com/maddyjpw/

# Contact settings
contact_img: /assets/images/loopprofile.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: The Loop
    bio: The loop is bored in quarantine.
    url: http://google.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
